# Modified from https://kodimensional.dev/github-actions

name: CI

on:
  pull_request:
    types: [synchronize, opened, reopened]
    paths-ignore:
      - "**.md"
      - "*.sh"
      - "CONTRIBUTORS"
      - "LICENSE"
  push:
    branches:
      - 'master'
  schedule:
    # Additionally run once per week (At 00:00 on Sunday) to maintain cache.
    - cron: '0 0 * * 0'

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.10"
          - "9.0"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
        # TODO: HsOpenSSL fails to build on Windows and macOS without openssl.
        # include:
        #  - { os: macOS-latest,   ghc: "9.8" }
        #  - { os: windows-latest, ghc: "9.8" }

    steps:
      - uses: actions/checkout@v4

      - name: Set up GHC ${{ matrix.ghc-version }}
        uses: haskell-actions/setup@v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Configure
        run: |
          cabal configure --enable-tests --enable-benchmarks --enable-documentation
          cabal build --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        run: cabal build all --only-dependencies

      - name: Save cached dependencies
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Test
        run: cabal test all

      - name: Documentation
        if: matrix.ghc >= '9.4'
        run: cabal haddock

  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          # GHC version must match https://www.stackage.org/nightly
          - stack: "latest"
            ghc: "9.8"

    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        name: Setup Haskell Stack
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Configure
        run: |
          cat <<EOF > stack.yaml
            packages:
              - '.'
            resolver: nightly-2023-06-27
            extra-deps:
              - 'test-framework-hunit-0.3.0.2'
              - 'test-framework-quickcheck2-0.3.0.5'
          EOF
          stack config set system-ghc true --global
          stack config set resolver nightly

      - uses: actions/cache@v4
        name: Cache
        with:
          path: |
            ~/.stack
          key: ${{ runner.os }}-${{ steps.setup.outputs.ghc-version }}-stack

      - name: Install dependencies
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build
        run: |
          stack build --test --bench --no-run-tests --no-run-benchmarks

      - name: Test
        run: |
          stack test
